### PR TITLE
Island Biome with Three sub-biomes

### PR DESCRIPTION
**Pull request by Vuris**
My first pass at a lot of test biomes with world builder.
Mostly  designed around lots of water and islands with varying degrees of islandness and ease of traversal.
Enjoy the chaos.

### CODE REVIEW

**Comment by nevir** [comment]
Chaotic indeed!  That waffles sub-biome is especially nuts:

image

I think you may have checked in an older copy of the biomes though.  The version you've got here has only two sub biomes, and is missing noise functions for the biome selection:

image

Unfortunately, when rendering the main biome node, it ends up creating a blank world.  Mind pushing up your latest changes?

**Comment by nevir** [comment]
Some screenshots for those following along:

# Waffles sub-biome

image

# Floating islands of mountain sub-biome

image

**Comment by nevir** [comment]
Some feedback on the biomes:

Waffles:
- I'm not quite sure about using wood throughout the terrain like this :P  It looks great from the side, but from top down seems a bit too regular (all the trunk cross sections) - but I see why it's called waffles!

Floating islands:
- The floating islands are pretty cool!
- You might want to soften the mountains a bit; they're very steep and pretty hard to climb.
  - Maybe also make them larger on average, so that they reach closer up to the floating islands?
- Also, try adding some noise to the heightmap - they're too smooth to be believable, IMO

**Comment by Vuris** [comment]
I'll go ahead and double check my world builder. Had no idea I set waffles do it as trees, though I honestly find that one pretty hilarious. Like I said growing pains :3Though looking at them, I dont see the trees on the island, which is leading me to believe this is one of my earlier edits, before I figured out the trees and cave system.The islands... where a hard one to pull off what I wanted.Looking at the colours, yea. Thats an older copy. Not what I wanted to give you. I'll push a new one through then.

**Comment by Vuris** [comment]
Not sure if I'm doing this right, do I just update the new file and click the push button on GitKraken and it'll update any changes I've made?

**Comment by nevir** [comment]
> Not sure if I'm doing this right, do I just update the new file and click the push button on GitKraken and it'll update any changes I've made?

Ah!  Yeah, you need to repeat the last few steps to create another commit:
- Hit "Stage all changes" in GitKraken, which will pick up anything you've changed since the last time
- Fill in a message (you can be brief) and then hit "Commit"
- Push the commit up to GitHub (via the push icon or menu option)

At that point, your commit should show up on this page

**Comment by Vuris** [comment]
Well went ahead and pulled out the old ones and pushed in the new ones. Double checked things on the WB to make sure this is the most recent version I was working with.

**Comment by nevir** [comment]
sweet, thanks!  I'll poke around once I get home

**Comment by nevir** [comment]
I haven't forgotten about this! Work ate me alive. Will review soon!

**Comment by Vuris** [comment]
No worries, I've been tinkering around with the islands a bit. Trying to smooth the peaks out like you said and lower them closer so you can actually grapple onto them from most of the islands. Kinda want falling off from them to be a possible headache/possibly a death sentence due to the water and future fishy inhabitants below.

**Comment by nevir** [comment]
> Kinda want falling off from them to be a possible headache/possibly a death sentence due to the water and future fishy inhabitants below.

Ha, nice!  Well, another approach that might make sense there is to have smoother tops, and have steep sides?

**Comment by nevir** [comment]
Got around to poking around with this some more - it still looks like you're missing the third sub biome, at least in the copy on GitHub :(  What does your biome look like when you preview the main biome node?

image

(the chunks preview, here)

Other feedback: The islands feel better, now, with the extra detail on them!

(if you want, also feel free to email me biome configs - ian@nevir.net - and I can help incorporate them into this repo)

**Comment by Vuris** [comment]
Imma go head and shoot you the email.
Github and kraken aren't liking my uploads as you've pointed out, which I find odd.

**Comment by nevir** [comment]
Some WIP screenshots via email, for those following along:

image
image
image

It's progressing nicely!

**Pull request closed without merging**
