### PR TITLE
Added Evergreen prefabs

### PR DESCRIPTION
**Pull request by MatthewSandford**
Evergreen (an external voxel design studio) created some prefabs for us to use throughout our worlds. These are the new prefabs to merge.

### CODE REVIEW

**Comment by nevir** [comment]
Oh awesome!

**Comment by nevir** [comment]
no comments here - merging like mad

**Comment by DamTerrion** [comment]
👍👍👍

**Comment by nevir** [comment]
👍 👍 👍 👍 👍 👍

**Pull request merged**
