### PR TITLE
First pass biomes

### PR DESCRIPTION
**Pull request by MatthewSandford**
Initial set of biomes for review.

### CODE REVIEW

**Comment by nevir** [comment]
!

**Comment by nevir** [comment]
These look freakin' fantastic!  Awesome work.

I think we should merge this as is, and any feedback can be applied as separate pull requests.  Should be more manageable that way given the sheer volume of biomes we're talking about here :P

---

However, here's my notes, and screenshots for anyone following along:

# General Comments
- There's a lot of duplication of node subtrees; especially for decoration selection.  We should totally break some of those out into shared node functions!
- Awesome job adding a bunch of options for these biomes; that's going to help a lot to make the worlds feel more varied.
- I think most biomes' strata would benefit from a little depth & distribution noise so that they don't have smooth edges - currently the strata layers feel a bit "painted on"
- Most of the biomes don't stray very far vertically - we should probably shift some of the biomes to higher y-heights
- A lot of the decoration nodes are going to need to have minY specified (e.g. so trees don't spawn under water)

# Bog

image
- I wonder if it could use _some_ noise for the heightmap so that the bog surface (and ponds) aren't completely flat?
- I really like this one!  It's sparse

# CarvedDesertMountains

image
- Gotta say, not a huge fan of the distortion on this one; it's way too regular (e.g. at a given z value, all the mountains are distorted in the same direction for large xy regions)
- The heightmap on this one is pretty cool; good mix of "lowlands" and mountains to keep it interesting

# ChocolateHills

image
- The ditches might benefit from a bit of (2d) distortion? They seem too smooth/round atm?
- Interesting how they go down to the bedrock! Could be fun (esp caves)

# Coral

image
- This is a neat biome; though I'm not sure how well it works w/ the current set of assets:
  - Thorns don't seem to work under water (it looks like they create air pockets)
  - I'm not so sure about the glacier trees/shrooms :P
- Might want to just tone down the size of all the decoration nodes? (lots of tiny 3-4 block tall spikes instead?)

# DeepSea

image

# DesertCanyons

image
- Simple, but very neat!
- I think it would benefit from some patches of thorny grass

# DesertRockOutcrops

image
- Woah

# HexShallowSea

image
- Spiky!
- Feels like it could use some more detail between the spikes (maybe try the dunes noise?)

# HighIslands

image
- Hmm; maybe try interpolating the terrain so that islands near each other blend together more?

# IceCrack

image
- Definitely needs moar heightmap, but this is neat!
- Also, maybe raise the min height up a ways? This would probably make the most sense at high altitudes?

# IceForest

image
- Winter wonderland!
- The hexes are a bit too regular :P

# IceSheet

image
- Nice! Feels like Alaska
- IMO the sheets should be _much_ smaller (and more frequent) - or you're going to want this to be a _very_ large biome

# LowIslands

image
- Peaceful!
- Might be good to add some depth noise to the grass so that it doesn't have a smooth edge between it and the rock in the center of the islands

# Mangroves

image
- Wow!
- This will only get better once we have prefab mangrove trees!

# MudFlats

image
- I wonder if there should be some small shrubs that spawn inside the cracks

# Oasis

image

# PeatySwamp

image

# Rainforest

image
- Tough to do a real rainforest w/o some better trees - prefabs to the rescue!
- I'm wondering if you want to combine all the rainforest biomes into a single one with sub-biomes?  
  - This one is pretty bland on its own, but would look great when mixed in w/ the other ones
  - It would also let you share plantations and such between the various sub-biomes, rather than having to copy/paste the configs (esp if you want to make tweaks to them)

# RainforestCliffs

image
- People are going to have fun building hidden things here!

# RainforestGorge

image
- Those are some pretty steep river banks!  This is going to be a bit annoying to travel through

# RainforestRiver

image

# RockyDesert

image
- Woah! Really cool terrain

# SandDunes

image
- Welp, I'm convinced about using sine waves!

# Savana

image
- Nice!
- Maybe also have a few small (and rare) ponds strewn about?

# SeaTrench

image
- Great. Now I want to go build a sea base.

# SeaVolcano

image
- Ha!
- Could probably use some distortion so the mouth isn't so regular

# SemiArid

image

# Shallow Sea

image

# TieredLakes

image
- Neat concept
- Those steep sides are going to suck to grapple or dig up through :(

# TundraMountains

image
- Scratch the sea base; I think I'm going to have to go make a log cabin in the woods now.

# TundraRiverForest

image
- Some small/low shrubs might help spice this one up?

# WaterForest

image
- Swampy!

**Comment by deltaluca** [comment]
My issue is that a lot of the biomes have very, very, very large trees in them, and we've tried to push towards smaller trees generally recently to avoid the world looking too small (mountains can only be 100-150m tall, kind of weird to have trees that are 40m tall etc.)

**Comment by nevir** [comment]
> My issue is that a lot of the biomes have very, very, very large trees in them

Good point - the giganto-trees probably only make sense in the rainforest biomes (and we really need prefabs for those anyway, or whatever else you guys are cooking up for trees)

**Comment by MatthewSandford** [comment]
Thanks for the feedback nevir, very thorough.  I will make a few comment of my own: 
- We are currently considering what we want to do with strata so they are rather basic. 
- Some biomes are flat for contrast. Make things easy to build. I agree it doesn't look as interesting.
- The chocolate hills are actually completely different. They are supposed to be hills and not ponds (I must have default value wrong) 
- Agree on the coral!
- Mudflats is utter trash, I just wasn't imaginative enough.
- Oasis is all under water so that when it is merged with other higher biomes a lake is created in the middle (may be a better way of doing this)
- Volcanoes need some work, they don't blend well into other biomes (mouth of volcano is not centred)

I like most of the suggested changes and will be updating the biomes today!

**Comment by nevir** [comment]
> Oasis is all under water so that when it is merged with other higher biomes a lake is created in the middle (may be a better way of doing this)

I think for biomes like this, we should actually create them as biome parts, and then tie them together in a main biome via sub-biome selection

> Volcanoes need some work, they don't blend well into other biomes (mouth of volcano is not centred)

Do we have the ability to do that w/ the world generator currently?  Would be useful to have some values offset by biome selection (though, the code behind that seems ...complicated)

**Comment by DamTerrion** [comment]
> Winter wonderland!
> The hexes are a bit too regular :P

I like it!
Seriously, it's all so great

**Comment by MatthewSandford** [comment]
We are closing this request as we are moving all our config files into a new branch. This branch will be for biomes that will not run on the currently release version world builder. When we update the builder we will send a pull request to merge that branch into the community repository.

**Comment by nevir** [comment]
👍

**Pull request closed without merging**
