### PR TITLE
Renamed some files with correct spellings.

### PR DESCRIPTION
**Pull request by MatthewSandford**
We are only human!

### CODE REVIEW

**Comment by deltaluca** [comment]
This would however, break all configs referencing the old names ;)

**Comment by MatthewSandford** [comment]
I don't believe we use any of these prefabs in our worlds.

**Comment by DamTerrion** [comment]
Honey British =)

**Comment by nevir** [comment]
Found some more now that I'm poking around with this stuff again (glasier, etc) - are you guys using any of these internally yet, or would I be safe to rename?

Also, holy crap these prefabs are awesome!

**Comment by olliepurkiss** [comment]
Happy New Year!
Sorry for the delay, we've been off over Christmas. @MatthewSandford can tell you if we are safe to rename, although he's not back in until next week. Are you ok to wait until then?

**Comment by MatthewSandford** [comment]
Yo,

Glacier can be renamed very safely, I am pretty sure I haven't used that yet. Any others should be fine to rename. I will just make sure the nodes are updated when you are done.

**Comment by MatthewSandford** [comment]
Nevir, do you have a list of the prefabs spelt incorrectly? I'm doing some tidying and rearranging at the moment so might as well add the corrections as well.

**Comment by nevir** [comment]
Yeah, sorry, I dropped the ball on this one & haven't been able to get to it :(

Some of the ones I saw:

* lusterous -> lustrous
* arcacia -> acacia
* mamoth -> mammoth
* staligmite -> stalagmite
* iglo -> igloo

and a few odd commenty ones like "_mang" and "_no_shizzle"

Oh, and _clearly_ the u in colour is wrong :P

**Pull request merged**
